### ISSUE TITLE
Posting URL

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#110]
In progress:  creating posting URL to our site.

**Comment by ehodul** [comment]
Sample posting URL:
http://www.universities-colleges-schools.com/receive_contact?SID=1016&WID=1017&AN=XY743&ProgramID=12838&CampusID=224&FirstName=test&LastName=test&Email=test%40gmail.com&Telephone=6044445555&City=Port+Moody&ProvinceStateID=BC&CountryID=CA&ExpectedStartDate=2015Oct&Comment1=TEST+ONLY&checkBox=Y&&IsTest=Y

Where SID is school node ID, WID is webform ID, AN is affiliate number.
This URL (used by affiliates) does not contain SourceID or TID, these will be added before submission to lead centre - based on the SID parameter.

**Comment by ucem** [comment]
To ensure I understand, we would assign SID, WID and AN?  Should they all be numeric, and how many digits or does it matter?

**Comment by ucem** [comment]
OK, I see affiliate # is the one I assigned, just unsure of the other 2

**Comment by ehodul** [comment]
Please have a look at the attachment I sent in my email today - posting
instructions for the affiliate.
SID is school node id
WID is webform node id
AN is affiliate number you assigned.

In that document, all values are set for this affiliate and this school.
