### ISSUE TITLE
Web Form Alignment Issue

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#111]
I've seen this alignment issue occur occasionally in Web Forms.  Is this a bug?

(not naming school so Google Alerts doesn't pick it up!!)
http://www.universities-colleges-schools.com/node/1082/edit

![screen shot 2015-02-03 at 1 41 36 pm](https://cloud.githubusercontent.com/assets/2644526/6030213/ccbea6a0-abaa-11e4-8ecf-7f3414bd1ddc.png)

**Comment by ehodul** [comment]
Styling issue, fixed.
