### ISSUE TITLE
Disabling or Making Optional - School Detailed Program Info

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#112]
we're just curious as to how much work it would take if we chose to make the School Detailed program info optional.  It ties into many things, but some schools have the exact same programs as many others and its often difficult to write individual content.  

It's probably too complex an endeavour unless we want to redesign the site, but thought we'd ask.

**Comment by ucem** [comment]
Just revisiting this to see how what it would take and how many hours?  

In order for a school page (with programs) to show up on a career page, a program page must be created.  What could we do so that if we wanted to create school pages only, list all the programs in the content and somehow link to the appropriate career pages.

**Comment by ehodul** [comment]
It is a very complex endeavour, we will have to revisit the whole structure of the site, I am trying to figure out how to keep this as simple as possible. 
If we wanted to create school pages only, list all the programs in the content ( or keep them as they are, but only link them back to school and simplify, remove some fields ) and link to the appropriate career pages, we could start buy adding a 'Careers' field directly to the school content type and change related queries. My rough estimate would be 6-8 hours of development and testing. It might be worth doing though, it would greatly simplify many things.

**Comment by ucem** [comment]
When you say "we could start buy adding a 'Careers' field directly to the school content type and change related queries" does that mean that if we do only that, we could start the process without a restructure or we would have to redo the whole structure?

**Comment by ehodul** [comment]
This would be a first step. This would change many things. Content structure, search by career, queries on career pages etc. Then we can continue by moving all locations to school, changing all queries (search by country, search by location, city,..) and making the search results based on school information, not programs.

**Comment by ucem** [comment]
Ahh, hence the 6-8 hours.  We're beginning to wonder if a whole site re-design would be more cost effective instead of piece by piece.  I don't know how much code you'd have to rewrite, what you could use. etc.  Thoughts?

**Comment by ehodul** [comment]
I would suggest to do this piece first as it seems to be an important change and overall simplification of content structure and design. We can reuse what we did in the whole site re-design.

**Comment by ucem** [comment]
Thanks for the info, will let you know if/when we decide to proceed.

**Comment by ucem** [comment]
Some additional questions.  If the first step is to make program pages optional, a) what would happen to current program pages, would they remain as they are and b) would the lead form work as it does now.  ie. When a program is selected, only the locations it is offered in is displayed in the drop down. 

"If we wanted to create school pages only, list all the programs in the content ( or keep them as they are, but only link them back to school and simplify, remove some fields ) and link to the appropriate career pages, we could start buy adding a 'Careers' field directly to the school content type and change related queries."

**Comment by ehodul** [comment]
a) current program pages can remain as they are. Only the searches will work (search) on content in school (as opposed to location/career specified in program).

b) the lead form would work as it is now if current pages remain as they are.
