### ISSUE TITLE
Web Forms - Adding Page Breaks

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#116]
Noticed that there is the option of adding Page Breaks to Web Forms.  We see a high bounce rate from the some Web Form pages and think visitors may become daunted by the forms that have many mandatory fields.  Industry practice landing pages have the web form split into 2 or possibly even 3 sections.  

I tried it on a non-client school to see how it works. The only problem I see is that the Submit Button is in the same place as the "Continue" label and the form can't be submitted anyway if all the fields are note completed. 

What would it take to move the Submit button over to the right IF we chose to add a break into the long forms?  It would also require not showing the Submit button on the first page of the form.

![screen shot 2015-03-03 at 11 38 48 am](https://cloud.githubusercontent.com/assets/2644526/6470650/ffedd460-c199-11e4-9aae-034fa465bdf1.png)

**Comment by ehodul** [comment]
This might be more work than it seems, since there is some background form altering and processing in our lead forms. I will have to do some testing to determine if it would be even possible without substantial changes in the way the lead forms are handled now.

**Comment by ucem** [comment]
Let me know what you find out.  Thanks!

**Comment by ucem** [comment]
Revisiting this as we've done a lot of digging into our analytics and visitors are going to the request info page and then dropping.  We believe it could be because once they see the form (especially for some that require a lot of fields) it may seem like too much work.  

This is a good eg. of what we'd like it to be like.  
http://information.devry.edu/uni/request-information.html?vc=140172

**Comment by ehodul** [comment]
That is a very clean and very short form.
We considered multistep webforms before (https://www.drupal.org/node/324779), but it has some issues and current way of processing (hacking) our webforms does not allow this.

Other possible solution might be to use CSS (styling) and some client side processing to divide form into two and hide/show only what is relevant for current step. I will try to create some examples of this.
