### ISSUE TITLE
Leadform - Node 1017 (Tor Film)

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#117]
The preferred program field is auto populated with -Select- as it should be but the CampusID automatically shows 1 of the 3 campuses instead of -Select-. If you click on Campus first it shows select but the ProgramID field goes to blank instead of showing -Select-.
The 3 campuses at this school all have the same location ID, so not sure if that is the issue?

**Comment by ehodul** [comment]
The problem is in Campus ID - the same ID for all three campuses. This will not work.
I changed temporarily the ids to 224-A, 224-B and 224-C - it seems to be working now. This is, of course, sending incorrect value now. I can make some workaround in the back end for this issue.

**Comment by ucem** [comment]
Will it take long?  We have a campaign running right now.

**Comment by ucem** [comment]
The more I think of it, i'm going to remove the 3 options and only have the one option as per their posting instructions.

**Comment by ehodul** [comment]
I was just working on a workaround... It would be the best though to stick to their posting instructions.

**Comment by ucem** [comment]
It will make it simpler than having something in the back end.  I didn't realize having the same Campus code would cause a problem.  Sorry for the trouble :-(
