### ISSUE TITLE
Googlebot

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#118]
Do we allow Googlebot (within the robots.txt file of a website)

DESIGN & SEO: Don’t believe that Web design plays a role in SEO? Think again. In late 2014, Google announced that its indexing system started rendering pages similar to a modern Web browser; that means with JavaScript and CSS turned on. To ensure that a website is rendering correctly and being indexed properly, allow Googlebot (within the robots.txt file of a website) to access the design-related files that are being used in the page. Google has warned that preventing (e.g. disallowing) Googlebot from crawling these files can result in sub-optimal rankings as it impacts how the search engine’s algorithms render and index content. - See more at: http://www.websitemagazine.com/content/blogs/posts/pages/you-me-and-the-googlebot.aspx?utm_source=newsletter&utm_medium=email&utm_campaign=newsletter#sthash.a5OQzyRH.dpuf

**Comment by ehodul** [comment]
This is our robots.txt:
http://www.universities-colleges-schools.com/robots.txt

All of our site design and files are in the /sites/ directory, which is allowed to be accessed.
We should be fine.

**Comment by ucem** [comment]
Thanks!
