### ISSUE TITLE
Web Forms - Can they be sorted Alphabetically

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#119]
Both here  /admin/content/webform and here /admin/config/custom_lead_form_urls

**Comment by ehodul** [comment]
Yes, they can. I will work on this tomorrow.

**Comment by ehodul** [comment]
Done.

**Comment by ucem** [comment]
Perfect, much easier to work with.  thank you!

**Comment by ucem** [comment]
Yesterday I noticed they are no longer alphabetical. 
admin/content/webform 

Can you tell me where to correct this so I don't have to keep bugging you as it seems to happen often.
Thanks!

**Comment by ehodul** [comment]
There was a new recommended webform module update that I did recently. This resets the sorting to the one that comes with the module. I will add it to the code again.
