### ISSUE TITLE
Search by Location (Province, City) - School Link Errors

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#120]
When you search by Province and City (regardless of which province/city), the correct schools are returned, however they all link to the same school.  I recall that we've had this issue before but I think it was before your time.

http://www.universities-colleges-schools.com/search-by-city/Calgary

**Comment by ehodul** [comment]
What do you mean by 'they all link to the same school'? I can not find any problem on the search result page.

**Comment by ucem** [comment]
Sorry I should have been clearer.  If you click on the logo, it goes to the correct school, if you click on the school name beside the logo, they all go the the art institute
![screen shot 2015-03-18 at 10 42 38 am](https://cloud.githubusercontent.com/assets/2644526/6715428/a524f8c4-cd5b-11e4-90af-fb088ae6fc90.png)

**Comment by ehodul** [comment]
I see now! Thanks for the explanation. I will try to fix this ASAP.

**Comment by ehodul** [comment]
Fixed. Please review. 
It must have been 'before my time' :), the art institute was hard coded there.
