### ISSUE TITLE
Lead Form - Posting URL for Sullivan

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#122]
School Node 1214
Form Post instructions being sent to you via email.

Another school posting to Sparkroom.  Need to change the Campus and Program ID to their requirements.  Thanks!

**Comment by ehodul** [comment]
Updated the code according to the received attachment, please retest.

**Comment by ucem** [comment]
Received Error code 400 which I can't see in the FPI so not sure what it is. Also, the program selected is not being recorded in our database.  If I add the field "Select Program" with their field key "program" the selection shows up 2x in the web form.  (I always have this problem :-(

Return error: Bad Request
Return code: 400
Return status_message: Bad Request

![screen shot 2015-04-13 at 1 58 39 pm](https://cloud.githubusercontent.com/assets/2644526/7125393/3c501a4c-e1e5-11e4-8909-296651a768e4.png)

**Comment by ehodul** [comment]
Please try now - I tried and it came with code 200 (OK).

**Comment by ucem** [comment]
Tests went through, made some tweaks (error with Express Consent), also can't use Test in the name field, this time we're getting an Error SR530 (Over Cap), not sure why.  Will check with them, and in the mean time when you have a chance can you add the program field so we can capture it?

**Comment by ehodul** [comment]
Done. Added fields. Tested.

**Comment by ucem** [comment]
Submitted another test lead today, it went through ok.
