### ISSUE TITLE
Miscellaneous Clean up Items 

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#123]
Career Page and Program Page 
1. Request Information Text - It looks like the font is Times New Roman instead of Arial
2. Field are right justified instead of left justified - can this be changed to left justified

Program Page
1. The gap between the end of the content under program information and the campus information seems to be larger than it used to be.  Can we tighten that up a bit?
![screen shot 2015-04-10 at 1 09 55 pm](https://cloud.githubusercontent.com/assets/2644526/7095895/0fabb33e-df83-11e4-89a3-4604b2ce93d4.png)

**Comment by ucem** [comment]
career/Payroll 
If the school name is really long, can it be made to wrap around?
![screen shot 2015-04-14 at 4 01 37 pm](https://cloud.githubusercontent.com/assets/2644526/7149232/a9aaf898-e2bf-11e4-9582-016bba96f75f.png)

**Comment by ehodul** [comment]
I tried to address some of these issues, please review.

**Comment by ucem** [comment]
Looks good, I think the only thing open is the program page spacing.
