### ISSUE TITLE
Captcha Alternatives in Drupal

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#124]
Are there different Captcha alternatives available other than the typical awful letters/numbers?   On one site (can't recall where), I saw one that asked you to select the square or circle from images.  

Also, can we implement it on only selected web forms?  
Don't know if we'd implement it anyway at this point, but we're seeing some spam and unfortunately they go through to some clients.

**Comment by ehodul** [comment]
Alternatives:
https://www.drupal.org/project/mollom
http://portal.areyouahuman.com/installation/drupal
https://www.drupal.org/project/botcha
