### ISSUE TITLE
Site or Google Analytics Hacked?

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#126]
Since yesterday, we've been seeing these pages listed in our Google Analytics.  Not sure if the site was hacked or Analytics was.  Would you be able to see if the site was hacked.  If not and it was Analytics, do you know how we could fix this?  
![screen shot 2015-04-22 at 10 36 23 am](https://cloud.githubusercontent.com/assets/2644526/7280993/83e22b28-e8db-11e4-8e78-f8a358ec2c04.png)

**Comment by ehodul** [comment]
I will have a look at this ASAP.

---
Erika Hodul
HERA Consulting Ltd.

Tel: 604 469 9363
Mobile: 604 339 8048
ehodul@heraconsulting.ca
www.heraconsulting.ca

**Comment by ucem** [comment]
Is it possible that this is referrer spam?  I just had 13 visitors that were referred from free-share-buttons.com and found some info. 

http://www.ohow.co/block-social-buttons-simple-share-buttons-referral/
http://blog.raventools.com/stop-referrer-spam/
Note:  We also have referrals from semalt which looks like it is not a good thing.

**Comment by ucem** [comment]
Actually I think it is.  I see referral traffic from 
social-buttons.com
buttons-for-web-sites.com
free-share-buttons.com
sexyteens.hol.es
buttons-for-your-website.com

Will adding code as suggested here http://blog.raventools.com/stop-referrer-spam/ help?

**Comment by ehodul** [comment]
Could you try to do the following suggestion from the post?

...Georgi Georgiev pointed me to his post that analyzes all of the options for blocking referrer spam. He concluded that the best overall solution is to create a custom filter in Google Analytics.

You can create a filter for your sites in Google Analytics by navigating to the Admin and then clicking on All Filters. Click on the New Filter button and then create a Custom Exclude for Campaign Source. Enter the domains you want to exclude using Regex. The format should be domain./ followed by a pipe (|) for each additional domain.

darodar\.|semalt\.|buttons-for-website|blackhatworth|ilovevitaly|prodvigator|cenokos\.|ranksonic\.|adcash\.|simple-share-buttons\.|social-buttons\.

**Comment by ucem** [comment]
Thanks.  I did some reading last night and did add a filter for the buttons referral sites, and will modify it to include some of these others.
