### ISSUE TITLE
Redirecting Users to Affiliate Landing Page to Complete Their Web Form

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#130]
We may be working with a new affiliate where we would redirect users to complete certain school's lead forms on the affiliate's landing page.  This would mean:

School Page - The Request info button would link to the affiliate page (easy enough), and so would the request info button under the school name that is found on the search by Category (schools/animal-science) and also Area of Study Pages (business-programs-and-courses/accounting-and-finance)

Program Page - Web form on right would disappear and info button linking to affiliate would have to be put back on the program page.

Career page - this is where it might get tricky.  Web form on the right would stay as is for the schools this change would not apply to, but for schools that we would be sending leads through the affiliate, when they select that school from the drop down, the web form disappears but  the button with link to the affiliate's page appears.

Web Form page - if it currently exists, it would have to be disabled so users can't get to it.

Also since there are many US schools that we could only access through an affiliate, we'd have to make it somewhat easy to do this in the future without a lot of back end work. 

We'd also need to have some kind of pixel so that we know when a user goes to the affiliate site.
Hope this makes sense. 

Could you please let me know how difficult this is to do, time involved, and how soon it could get on your schedule?

**Comment by ehodul** [comment]
I will get back to you with work estimates tomorrow.

**Comment by ehodul** [comment]
Work estimates:
- school pages, program pages: 3 hours (add a flag to school or webform for given school, that the school form is accessed through affiliate only, add a link to affiliate page, modify pages where appropriate, testing)
- career pages: 4 hours (modify search by career module, hide/show webform or 'request info' button based on school settings, modify related JavaScript)
- webform page: 1 hour (disable webforms for schools that go through affiliate, modify webforms to add 'affiliate only' flag)
- 'some kind of pixel' - 2 hours to create some way to administer and process callbacks from pixels

I can start working on this at the end of next week.

**Comment by ucem** [comment]
thanks Erika. We will see how quickly we can get an agreement with the affiliate in place, so don't put it on your schedule for next week yet.  We'll give you as much lead time as possible,
