### ISSUE TITLE
Problems were detected with your Drupal installation. 

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#131]
One or more problems were detected with your Drupal installation. Check the status report for more information.

http://www.universities-colleges-schools.com/admin/config

**Comment by ehodul** [comment]
I will do the system update (no security update, just recommended update). Is it OK to put in maintenance mode right now, or it would be better to do this tonight?

**Comment by ucem** [comment]
Probably best to wait till tonight as we are running some campaigns now.  How long would it be down?

**Comment by ehodul** [comment]
15 minutes

**Comment by ehodul** [comment]
Closing ticket. Everything is up to date.
