### ISSUE TITLE
Meta Description Field Missing from all Pages

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#133]
All our meta description fields have disappeared from school, program and taxonomy pages.
Will you be able to retrieve them all from a back up so we don't have to start from scratch?

**Comment by ehodul** [comment]
Metatags are back. There was a metatag module update, after the update, it was necessary to configure the new settings (which content type should have metatag). I set this up now, it should work. Please review.

**Comment by ucem** [comment]
Thank you  for taking care of this tonight, I know it's late.  Very much appreciated!
