### ISSUE TITLE
School Page - H3 and Programs Offered Block

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#134]
I noticed that when creating Header 3 titles, the font looks quite different from the H2.  Originally when I looked at the source while in edit mode, I noticed this code on the first H3, but I edited it in the hopes that it would change it to arial but it didn't.
<h3> <font face="arial, helvetica, sans-serif">Business Programs</font></h3>

Is there somewhere that controls the font and size for these Headers?
![screen shot 2015-06-10 at 11 00 51 am](https://cloud.githubusercontent.com/assets/2644526/8089985/07f1f632-0f60-11e5-95ec-2b0fcbd2dc41.png)

Also, I wanted to remove the programs offered block from the bottom of the school page as it is redundant.  (I am adding the program names in the body of school information so I could create H2 and H3 Headers) but I'm not exactly sure how to remove it.

http://www.universities-colleges-schools.com/admin/structure/views/view/school_detailed_program_info_vie/edit/default?destination=node/270

![screen shot 2015-06-10 at 11 09 45 am](https://cloud.githubusercontent.com/assets/2644526/8090174/41329b94-0f61-11e5-9219-f048db2f3d6f.png)

**Comment by ucem** [comment]
Also wanted to note that H2 also looks different between various pages.  On career page /career/Pharmacy-Technician the H2 (What is a Pharmacy Technician?) is large and bold, the next one What Skills and Abilities Does a Pharmacy Technician Need? looks like regular text that is bolded.

**Comment by ucem** [comment]
I now know how to hide the programs offered, would you have time today to look at the Header formatting?

**Comment by ehodul** [comment]
Header formatting is done in the stylesheet. Some pages might introduce an exception in the style. 
I am not sure how can I help here. These are the styles for headers in current stylesheet:
```
h2 {
	color: #104d4d;
	font-size: 14pt;
	line-height: 20px;
	font-weight: normal;
	font-family: "ff-meta-web-pro";
	font-weight: bold;
}
h3 {
	font-family: "ff-meta-web-pro";
	font-size: 21px;
	line-height: 31px;
	margin: 18px 0 10px;
	font-weight: normal !important;
}
```

**Comment by ucem** [comment]
Just so I understand, this is driven by this theme's style and can't be modified so that H2 is a larger font that H3 and it can't be changed to arial.  Am I reading that correctly?

**Comment by ehodul** [comment]
I can modify the theme, but please let me know what is required. What would be the desired size for H2 and H3? I can also change the font to Arial or whatever, make it bold etc.

**Comment by ucem** [comment]
What is the font size for h1?  Our content text is Arial 12, so the font should be Arial, and the size of the H Tags should decrease the higher the number.  Can the line-height be the same for all, so there are no large gaps?

**Comment by ehodul** [comment]
```
h1 {
  font-size: 2em;
  line-height: 1.5em;
}
```

**Comment by ucem** [comment]
So if our regular font size is 12, 2em would be 24??

If that is the case h2 should be 22, h3-20, h4-18, h5-16, h6-15

**Comment by ucem** [comment]
Line height 1 em

**Comment by ucem** [comment]
Do you need more info from me?

**Comment by ehodul** [comment]
I will set the sizes as specified. I will keep current font for now, if you need to change it, please let me know. Also, H4 has a dotted line background. Should I keep or remove this?

**Comment by ehodul** [comment]
Test page with all headings:
http://www.universities-colleges-schools.com/test-page

**Comment by ucem** [comment]
Font should be Arial and no, 4 should not have the dotted line background.

**Comment by ehodul** [comment]
Changed all Headings to Arial, looks very plain now. It looked more interesting before. Please review the test page.

**Comment by ucem** [comment]
Heading 3 should be bolded as well to make it consistent, then it should be
good to go.  




From:  Erika Hodul <notifications@github.com>
Reply-To:  ehodul/universities-colleges-schools
<reply+00285a2e3011c1dbbb5d650689acee45ecd10cba0f1bd05692cf0000000111972c0b9
2a169ce05306333@reply.github.com>
Date:  Monday, June 15, 2015 at 5:12 PM
To:  ehodul/universities-colleges-schools
<universities-colleges-schools@noreply.github.com>
Cc:  UCEM Administrator <info@uc-education-marketing.com>
Subject:  Re: [universities-colleges-schools] School Page - H3 and Programs
Offered Block (#134)


Changed all Headings to Arial, looks very plain now. It looked more
interesting before. Please review the test page.


Reply to this email directly or view it on GitHub
<https://github.com/ehodul/universities-colleges-schools/issues/134#issuecom
ment-112242231> .

**Comment by ucem** [comment]
Is it me or is "this is heading 2" on the test page a different colour?  Its looks kind of a dark teal. 

Also, not sure if you're done, but the career page header tags (/career/Pharmacy-Technician) aren't being applied like they are to the school page node.

**Comment by ehodul** [comment]
Yes, Heading 2 was the same colour as it was before. I made it all black now. Fixed the career page styling.

**Comment by ucem** [comment]
I know we initially said we'd leave the hard coded h2 and h3 tags till we migrated to the mobile responsive site, but what I didn't realize, is that we get penalized for using heading tags as hidden text.  Is it major work to remove the tags on the various pages such as on the School page for eg. <h2 class="element-invisible">Primary tabs</h2>

**Comment by ehodul** [comment]
On school page, there are two h2 elements with class element-invisible:
<h2 class="element-invisible">Search form</h2>
<h2 class="element-invisible">You are here</h2>
I can try to remove these.
This is visible only to users with administrator role: <h2 class="element-invisible">Primary tabs</h2>

**Comment by ucem** [comment]
Is this a relatively quick fix?  How long will it take as we have others on the school page, program page and career page which are very important to change.

**Comment by ehodul** [comment]
This is part of Drupal system and it is not easily removable, nor it is recommended.

As stated in the comments in Drupal core modules/themes: 
"An invisible heading identifies the messages for assistive technology."
More info here:
http://www.w3.org/TR/WCAG-TECHS/H69.html

**Comment by ucem** [comment]
Its a little too high level for me, but I read this that one should " not use heading tags as hidden text. Any hidden text can result in penalties for your site, especially if the hidden part is a component that effects SEO."
Perhaps I am misunderstanding the meaning of hidden text??

**Comment by ucem** [comment]
What would your recommendations be and on the career page can you make 
h4>Schools offering Nursing Assistant Programs and Courses</h4 from an h4, to an h2 or would this not be recommended?

**Comment by ehodul** [comment]
Good article describing very clearly the issue here:
http://webaim.org/blog/web-accessibility-and-seo/
- see section "Off-screen Content"

**Comment by ehodul** [comment]
I will modify Career pages - h2 makes more sense there than h4.

**Comment by ehodul** [comment]
I modified the career pages (h2). Since there is such a small difference between h1 and h2 now (2 pixels only), it might be (visually) better to put back the old font (or add some colour) to h2. Please advise.

**Comment by ucem** [comment]
I see what you mean about the size variations. We're going to do a little more research on this and get back to you by Friday. 

As for the colours I believe I can change them as I did in /career/Pharmacy-Technician???

I haven't had a chance to read the links you sent but does it make sense to change the Welcome tag on the Home Page?

**Comment by ehodul** [comment]
I would suggest to remove the 'Welcome' and keep only the h1:
'Universities, Colleges, Career Colleges and Trade Schools in Canada and the US' 
... and keep the font and colour of the 'Welcome' for the above heading. 

As for the colours, it would be great if we can unify them throughout the website and set them up in the CSS.

**Comment by ucem** [comment]
Yes, lets remove welcome and I will spend some time over the next couple of days adding h2 tags to the various pages to see whether we should add some other styling as well as colour.

**Comment by ucem** [comment]
I've been looking at various recommendations for Header Tag sizes and do agree with you that visually there is a very small difference between h1 and h2.  You suggested putting back the old font family for h2 and I think it would be better to keep h2, h3 through to h6 tags fonts consistent even though we likely won't use 4-6.  What is the font for "Institute Information" in the school program page?  

Maybe we should change them to that font, change the colour to the original (color: #104d4d).  As for sizes this is what i've found.  Sorry for making you do this again, hope it's not very time consuming. :-(
h1 { font-size: 2em; }
h2 { font-size: 1.5em; }
h3 { font-size: 1.17em; }
h4 { font-size: 1.12em; }
h5 { font-size: .83em; }
h6 { font-size: .75em; }

**Comment by ehodul** [comment]
"Institute information" has class 'field-label' that has following styling:
```
.field-label {
  margin: 1.364em 0;
  font-family: 'MetaBoldLFRoman';
  font-weight: normal !important;
  font-size: 17pt;
  line-height: 1em;
  display: block;
  color: #004d4d;
  padding-bottom: .5em;
}
```
I can use the same font-family and colour for all headers if you like. 
We can at least try, it will look better. 
Or we can use font-family: "ff-meta-web-pro"; that is used on the home page.

**Comment by ucem** [comment]
Let's try your suggestion of the same font family and colour for all the headers Meta bold roman

**Comment by ehodul** [comment]
OK, please review. I did the font size according to your instructions and the font family and other styling as follows:
```
h1, h2, h3, h4, h5, h6 {
	line-height: 1em;
	color: #104d4d;
	font-weight: normal;
	font-family: 'MetaBoldLFRoman';
}
```

**Comment by ucem** [comment]
I'm out right now and looking at it on my phone so can't see it very well but it looks better. As soon as I get back home I will look at it my big screen and let you know

**Comment by ucem** [comment]
What are your thoughts?  Should we bump up h2 to 20 from 18, and h3 to 16?

**Comment by ehodul** [comment]
I changed the font sizes as follows, I think it looks good now.
```
h1 { font-size: 2em; }
h2 { font-size: 1.7em; }
h3 { font-size: 1.37em; }
h4 { font-size: 1.22em; }
h5 { font-size: 1.13em; }
h6 { font-size: 1em; }
```

**Comment by ucem** [comment]
I agree, thank you as always!
