### ISSUE TITLE
Field Label Change and Program Page

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#135]
Can you please tell me where to:
1. Change the Field Label from Find "Animal Care" Schools in Canada" to "Animal Care" Schools in Canada.
/animal-science-programs-and-courses/animal-care

2. Hide the campus listings on the program page.  I will still add campuses to the program page so that the appropriate campuses are listed to the corresponding program in the lead form, but we want to add the campuses in the program details so we make an Header tag and not have duplicate information.   

3.  Hide Label Program Information on program page.  Again, we'll create our own headers

**Comment by ehodul** [comment]
I removed 'Find' from Find Animal Care ... (it was in a script for some reason).
Campuses are not displayed on program pages now. Please review.

**Comment by ucem** [comment]
Can you tell me where you hid the campuses from the program page in case we want to add it back.  (We're experimenting)

**Comment by ucem** [comment]
In the career page can you change the label Schools offering Pharmacy Assistant as a Career to Schools offering Pharmacy Assistant Programs and Courses

**Comment by ehodul** [comment]
Yes I can. Go to Structure->Content Types->School detailed program info->Manage Display
admin/structure/types/manage/school_detailed_program_info/display 
And move fields around as needed.

**Comment by ehodul** [comment]
Changed career pages label to be like:
Schools offering Pharmacy Assistant Programs and Courses

**Comment by ucem** [comment]
Got it!  I see how to also hide the Program Information label.   
Thanks for updating the other field labels. Was the Schools offering Pharmacy Assistant as a career hard coded?

**Comment by ehodul** [comment]
Yes, the label portion 'as a career' was 'hardcoded' in the module.
