### ISSUE TITLE
Adding FB or Twitter Script or AdSense

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#136]
I think I know where to add script for campaigns but wanted to be sure because I could only see where you put in the retargeting code for NP Fashion Design.  I couldn't see where you added the conversion pixels for Yahoo or FB & Twitter.  Could you show me where that is?

Also is this the right place if I wanted to add FB tracking code?
Blocks
Add Block 
Click on "Source" of Block Body", paste in the script and on the page thank_you/Name of School
Does this thank you page need to be an actual link or just the way you have it in some of the other blocks.

We also cannot recall if this is where we should put any Adsense script??

**Comment by ehodul** [comment]
Yes, you have the correct block placement information. The thank_you/Name of School is how the thank you page URL is constructed when thank you page generated in the module. 

Some of the Blocks have also specified a Query (like tag=BIN3547) - 'Queries' can be specified at the very bottom of the block page (below 'Users').
 
When restriction by query is used, the url looks like
universiteies...schools.com/request-information/cdi-college?tag=BIN3547
- and the script is only shown on pages with this query.

**Comment by ucem** [comment]
It looks like I'm going to need your help on adding AdSense to select pages.  I've created a block called Ad Sense - Top 10 ...., added the script, and the two pages (currently 2 article pages) we are testing this out on, but this is where I am now unsure of what to do.  

We need to add the ability to have ads for the following sizes and locations. (I won't put the actual links here because its public so am inserting the nodes.)

The 728 x 90 Leaderboard one should go directly below the social media buttons and on top of the title of the article.  Top Ten Healthcare (node 332) and top-10-animation (node 1350)
We need the option of turning this off or on as we choose.

336 x 280
320 x 100
300 x 600 
The other three options will go in the right hand column right above the “search by Area of Study” 
For the 3 rectangle banners we’d want to select which one to use and may change from time to time.  We can only have a total of 3 ads on the page, so we need to have the flexibility to turn all of them on or off as we choose, so step by step instructions would be very helpful!!

**Comment by ehodul** [comment]
Do we have AdSense code for that? Maybe we could create blocks and show/hide them as needed.

**Comment by ucem** [comment]
Yes, I added the AdSense code to a block I started called Ad Sense Top 10...., but I will send the code via email.  Yes, creating blocks for the 4 sizes shown above that we could show/hide as needed would be great.
