### ISSUE TITLE
Pages Blocked by robots.txt

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#137]
Over the last few days I noticed our indexed pages are slowly dropping and see that under Blocked Resources in Webmaster Tools we now have some blocked URLS.

Not sure how or why that is occurring, but needs to be fixed.  I believe you should still have access to Webmaster Tools.  Can you please log in and have a look.  

Blocked resources are:
 > /misc/jquery.js?v=1.4.4
>/misc/jquery.once.js?v=1.2
> /misc/drupal.js?npfyhy
 > /misc/textarea.js?v=7.35
 > /misc/feed.png

I also did a Fetch and Render, looks like all pages aren't rendering correctly.

**Comment by ehodul** [comment]
I can log in to Webmaster tools. 
I can not figure out why these resources would be blocked.

**Comment by ehodul** [comment]
I updated robots.txt 
- removed (commented out) Disallow: /misc/

**Comment by ucem** [comment]
Thanks for doing this so quickly.  Any idea why this occurred and would this be why our indexed pages were falling?

**Comment by ehodul** [comment]
This looks like change in Google indexing algorithm. 
I hope the change will help.

**Comment by ucem** [comment]
The robots.txt were updated on June 17, and on June 19 these were still detected on the home page and our indexed pages have dropped from Friday to today. 

 /misc/jquery.once.js?v=1.2
 /misc/jquery.js?v=1.4.4 

Also only getting partial rendering with some "temporarily unreachable" errors.

**Comment by ehodul** [comment]
We can not do anything about the "temporarily unreachable" errors. The resources (mostly images) are all available now. Maybe the server was temporarily down at one point (when the particular page was being crawled) or there was another reason Google was not able to reach every resource on the particular page? It was able to reach the same resources on another pages and fully render the page.
I used the robots.txt tester and all js libraries (misc directory) are allowed.

**Comment by ucem** [comment]
Sorry to keep bothering you about this but I'm still seeing new blocked pages.  Some are new pages, some pages have dropped off this list. The Home page is consistently detected for the /misc/jquery.once.js?v=1.2 and /misc/jquery.js?v=1.4.4 and when I do the robots.txt tester it is indeed allowed. 

What exactly do these mean?  I tried researching, but it's all very technical and I don't understand it.
/misc/jquery.once.js?v=1.2
/misc/jquery.js?v=1.4.4
/misc/textarea.js?v=7.37
/misc/drupal.js?npuf7m

**Comment by ehodul** [comment]
To answer your question "What exactly do these mean?":
these are links to JavaScript libraries. The code in these libraries is used by Drupal to display/hide, traverse or manipulate page elements as needed.

I am still not sure why these are marked as blocked.

**Comment by ucem** [comment]
We're down to 6 blocked pages so will keep monitoring.  Thanks.
