### ISSUE TITLE
Unpublish Taxonomy terms 

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#138]
We don't have the option to unpublish taxonomy terms like we do nodes, and i'm assuming its because we don't have the Taxonomy Term Status Module?  

What would it take to load it (hours), what are the implications of loading it etc.  Not sure if we need it, but when the taxonomy terms were set up there were redundancies and even though we can forward them, they still show up in the list.  

Just wondering!

**Comment by ehodul** [comment]
I am not sure what our goal is here. Taxonomy terms are used for categorization of content. We do not need 'Taxonomy Term Status' module - we don't have users that we need to control (their access to use taxonomy terms when adding content) - it's only you updating the content.
Please clarify what needs to be done.

**Comment by ucem** [comment]
I was only thinking in terms of unpublishing a career.  As an eg. we have Computer information Technology and Information Technology.  I may choose to redirect CIT to IT, but CIT still shows up in the long careers list.

**Comment by ehodul** [comment]
I see. You need something to temporarily remove (unpublish) the career from careers list, then add it later if needed. I can add a field to Taxonomy to unpublish and then modify the career module to show only 'published' careers. Would that work?

**Comment by ucem** [comment]
Yes that would work.  How much time is involved?

**Comment by ehodul** [comment]
One hour or less.

**Comment by ucem** [comment]
Ok, please go ahead when you have time.  Thanks!

**Comment by ehodul** [comment]
Added field 'Hide career' to taxonomy items (in Career terms).
When this checkbox is selected, it will hide (unpublish) this career from the 'careers' page.
Please review.

**Comment by ucem** [comment]
I see under manage fields"Hide Career" but don't actually see an unpublish option  when I go into the career taxonomy.

**Comment by ehodul** [comment]
Try to select the checkbox "Hide Career" for one of the terms and you will notice that the career will disappear from the 'Careers' page. I did this for 'Computer information Technology'.

**Comment by ucem** [comment]
Now I see it.  Perfect!
