### ISSUE TITLE
Request Info Buttons - School Page

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#139]
It seems that the Request Info buttons aren't totally synced on School Page
http://www.universities-colleges-schools.com/admin/config/button_request_info 

Programs Offered is set to default (http://www.universities-colleges-schools.com/admin/structure/types/manage/school/display), the Request Info Buttons all show as they should.

If Programs Offered is hidden and Request Info Button is unchecked for Programs Offered, the button still shows twice at the bottom of the page. 

Note:  The Student Support field label was changed to Additional School Information quite some time ago in case you see that there is a discrepancy.

**Comment by ehodul** [comment]
I modified the school request button settings - deselected
 Institute Information
 Programs Offered

Now the button is showing on the page only twice as expected.
