### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#140]
Does our site use Google Search or some other search function.  If not Google, how difficult it is to change once we provide the Google Script?

**Comment by ehodul** [comment]
Our site uses standard Drupal search and then adds more school information, like programs (if school node found).
What would be the reason to add Google Search?

**Comment by ucem** [comment]
Wondering if we use Google search if it will help at all with ranking?

**Comment by ehodul** [comment]
Adding Google Search will not help with ranking. 

There are over 200 ranking factors mentioned in the article (most of them make sense):
http://backlinko.com/google-ranking-factors

Adding Google search to the site is not one of them.
