### ISSUE TITLE
Lead Submission Error Message

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#144]
Could this be a problem on the client's end.  We haven't seen this error before.
![screen shot 2015-10-16 at 10 12 13 am](https://cloud.githubusercontent.com/assets/2644526/10548300/8036141e-73ee-11e5-9ebb-b73cd1cb5689.png)

**Comment by ehodul** [comment]
Yes,
it looks like problem on clients end - $)$ is error where the page (URL to post to) can not be found. Perhaps they changed the URL?

**Comment by ucem** [comment]
Not that I'm aware of, but we will contact them.  Thanks.

**Comment by ehodul** [comment]
Even if I try to navigate to:
http://www.westervelt.ca/submitlead.aspx
- I get the same error - page not found. Could you please ask them if they changed the URL?

**Comment by ucem** [comment]
Do we need to program this in the back end to change sourceID to online source.
I changed the field key to online source but I think it might still transmit Source ID instead of online source.

" think the thing holding it back is changing SourceID: onlinesource to onlinesource: UCEM
We don't recognize SourceID but we do recognize the variable online source."

**Comment by ehodul** [comment]
I can change that in the backend.

---
Erika Hodul
HERA Consulting Ltd.

Tel: 604 469 9363
Mobile: 604 339 8048
ehodul@heraconsulting.ca
www.heraconsulting.ca

**Comment by ucem** [comment]
thanks Erika, let me know when it's done and I'll resubmit the lead.

**Comment by ehodul** [comment]
I updated the module and webform (field sourceID). 
This seems to be working now. Please review.

**Comment by ucem** [comment]
Thanks Erika.  When you say updated the module do you mean just for this web form, or does this mean we don't have to do back end programming for ProgramID and CampusID, SourceID anymore?

**Comment by ehodul** [comment]
Updated module just for this webform.

**Comment by ucem** [comment]
It worked!   Thanks.
