### ISSUE TITLE
Adding Script to Corporate Site

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#145]

**Comment by ehodul** [comment]
I changed the format to Full HTML. The script in the block you created seems to be inserted on the page (node/2) correctly. I even see the ads as expected sometimes. Not always though. I am not sure why.

**Comment by ucem** [comment]
I see an ad now.  Did changing the format to Full HTML hide the script?

**Comment by ehodul** [comment]
Yes, changing the format to Full HTML did hide the script. Yes, it should be possible to add to home page.
