### ISSUE TITLE
Custom URL Changes

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#147]
Several years ago a change was made to the custom URL module so that CampusID, ProgramID, TID and SourceID were automatic (works if client uses Lead Centre only) and if we had a client who uses a different format, you have to manually change it.

We talked about changing this back so that for each client I could add the required post parameter myself without you having to make changes individually each time.  Since we are seeing many new clients that use different formats, I'd like to see about changing this back as soon as possible.  

Can you tell me how long this would take and how quickly it could get done as I will have several new clients who for eg. instead of TID use LeadBuyer ID etc.

**Comment by ehodul** [comment]
I can have TID and SourceID done fast, but more time and testing would have to be allocated for ProgramID and CampusID, as these fields' names are used in the JavaScript library that changes the dropdown options (for program and campus).

**Comment by ucem** [comment]
Can you give me an estimate of time?

**Comment by ehodul** [comment]
Rough estimate would be 1 hour for non-drop down fields, 2-3 hours for ProgramID and CampusID, code updates, webform updates and testing.

**Comment by ucem** [comment]
Yes go ahead.  When do you think you can work on this?

**Comment by ehodul** [comment]
I am working on this today.

**Comment by ehodul** [comment]
I updated the custom lead forms URLs:
https://www.dropbox.com/s/70rlv7vfb2zduze/Screenshot%202015-11-13%2011.48.28.png?dl=0

- the SourceID and TID are obsolete here now, will be deleted soon (after your review), as the values are stored in the webforms now (in hidden fields with proper name according to the lead centre).

- two new fields added: CampusID field name, ProgramID field name - these names will be used for submissions now. The fields will be switched automatically right before submission. 

I tested the changes and it seems to be working fine. Please review and let me know how it looks from your end. Thank you!

**Comment by ucem** [comment]
Looks good.  
To clarify, if the CampusID field is to be transmitted as Campus for eg. all we need to do is name field key  "campus" in web form?

**Comment by ehodul** [comment]
No, we will keep CampusID and ProgramID fields in the webform. We will indicate on the custom lead forms URLs for the school, what the proper name will be. This name will be used for the submission.

**Comment by ucem** [comment]
Ok, got it!

**Comment by ucem** [comment]
I think there was a little bit of a misunderstanding.  We didn't want CampusID and ProgramID to be an automatic field as I can't control whether it's added or not. We'd rather create these fields as needed, just as we do with all the other fields. For eg. for a public school we may not want to put a campus as there is only one.  We also may choose to not add programs either. 

There also seems to be a bug. Eg. Westwood.  I deleted all campus locations from the school page and Anaheim still shows up as a default.

**Comment by ehodul** [comment]
I removed Anaheim campus and made CampusID field optional.

**Comment by ehodul** [comment]
I tried to make ProgramID optional as well, Program drop down field not be shown when no programs available, but I was not able to test this, as I can not find a school with no program. Please review.
