### ISSUE TITLE
Program & Career Page Webform - Campus Drop Down Menu

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#148]
Apparently the campus drop down menu on both the program and career pages, only shows Prov/State if a program is not selected.  This is not a big deal to us but a client did say that we were not in compliance.

Let me know how long it would take to fix this error, because if it's too much, we're going to leave it as is, and will tell them we'll fix it at a later date.

![campus selections with program selected](https://cloud.githubusercontent.com/assets/2644526/11287033/a200b7d0-8ecd-11e5-9fca-47f693bc9ce1.png)
![campus selections without program selected](https://cloud.githubusercontent.com/assets/2644526/11287034/a2057a90-8ecd-11e5-900a-2a57284579d5.png)

**Comment by ehodul** [comment]
Fixed (small update). This had always been like this on request info forms. Nobody noticed till now, it seems.
