### ISSUE TITLE
Webform 298 - Default Country Code

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#149]
![screen shot 2015-12-01 at 10 03 01 am](https://cloud.githubusercontent.com/assets/2644526/11509406/c1cf9eb6-9812-11e5-8fe6-9a862942aa9b.png)

Default country is set to Canada, but Afghanistan becomes default.  Tried deleting the field and re-entering, but same issue occurs.
(I know you're going away, so I can do a work around for the short term)

**Comment by ucem** [comment]
the same is happening when province default is set. 
![screen shot 2015-12-01 at 10 10 17 am](https://cloud.githubusercontent.com/assets/2644526/11509603/ceb3befe-9813-11e5-9e03-dc0e7f260d2d.png)

**Comment by ehodul** [comment]
I set default value to CA (key for Canada), the field shows Canada as a default now.

**Comment by ucem** [comment]
Is it because I spelled out canada instead of CA?

**Comment by ehodul** [comment]
I set default value to BC (key for British Columbia), the field shows British Columbia as a default now.

**Comment by ehodul** [comment]
The default value of the field is identified by its key.

**Comment by ucem** [comment]
Thanks!
