### ISSUE TITLE
Career Page - Dividing by Province/State

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#150]
Currently schools on the career page are listed by school ranking but I was wondering what would it take to also divide the career page by province/state?   Not sure if we should mix provinces/states and list alphabetically or list provinces alphabetically first, then states alphabetically.

Schools offering xx programs and courses: (possibly removing this h2 header)

xxx Programs and Courses in BC (probably making this an h2)
ABC School  (ranked 1)
DEF College (ranked 2)

xxx Programs and Courses in Ontario (h2)
XYZ College

xxx Programs and Courses in Chicago (h2)

xxx Programs and Courses in Los Angeles (h2)

**Comment by ehodul** [comment]
Work time estimate: 4 hours to modify search_by_career module to list schools by province/state (alphabetically, listing provinces first, then US states) and then by ranking (1 to 10).

**Comment by ucem** [comment]
Thanks, will get back to you.
