### ISSUE TITLE
Source Code Errors

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#153]
We've noticed error messages when viewing our source code which I believe has been there for quite some time (over a year) and I wondered if this is could in part be a cause in the drop of our pages in google. 

All pages have the "Failed to load resource: A server with the specified hostname could not be found" error and some have "Failed to load resource: bad URL".

I've attached screen shots of some errors we've found.

What is causing these, is this a real issue, and if so, what and how much time would it take to fix it?
![colleges page error](https://cloud.githubusercontent.com/assets/2644526/13684004/9904abf2-e6be-11e5-8619-3c6bc2b99d14.png)

![program error](https://cloud.githubusercontent.com/assets/2644526/13684005/99054260-e6be-11e5-8383-d43f665f95d5.png)

![screen shot 2016-03-10 at 12 35 26 pm](https://cloud.githubusercontent.com/assets/2644526/13684006/990b4ce6-e6be-11e5-9ee1-296e73e3b5b3.png)

**Comment by ehodul** [comment]
I am trying to figure out where these errors come from, I don't get the same errors on the same page (in Chrome (screenshot)), I will try Safari as well.
https://www.dropbox.com/s/bbv3vcndmcntsgh/Screenshot%202016-03-10%2013.03.10.png?dl=0

**Comment by ucem** [comment]
Wonder if its an Apple issue.  I'm in chrome on Apple and get a different error.
![screen shot 2016-03-10 at 1 12 46 pm](https://cloud.githubusercontent.com/assets/2644526/13684725/e0403c22-e6c1-11e5-8983-b518d6354260.png)

**Comment by ehodul** [comment]
I found an error when clicking on the 'Career colleges and trade schools' navigation button and also an error (the URL with help.png) when on program page, but only when logged in. When logged out, the help.png URL error disappears. I will go through the errors (whatever I can find) and I will try to fix them if possible.

**Comment by ucem** [comment]
If its only an error when logged in, perhaps its not important then????  If not, probably don't need to fix it.
