### ISSUE TITLE
Program Block on School Page (Right Sidebar)

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#161]
I'm in the Sandbox site and I know there is a View (Program Content), but when you click on the gear in the program block on school page, the only option is to Configure the block.

I tried moving that block to content as on some schools that have a lot of programs, there is a large white space in the content block.  Of course when I did that, the programs were listed in one long list.  I had also cloned, but have since deleted, the "block display" to play with and list the programs in 2 or 3 columns, but I couldn't get the programs associated with the school in the list.

Can you tell me how to do that?  thanks!

/evolve/admin/structure/views/view/programs/edit/block

**Comment by ehodul** [comment]
This block does not come from a view, but from a module (side_school_programs). The reason is, probably, that it was not so easy to configure a view where the programs would be listed by category. The question is: how to display the block in the content area in 2 or 3 columns instead of having it in the left sidebar. Is that correct?

**Comment by ucem** [comment]
Yes, that is correct. 

The other thing I'm toiling with, is whether we want/need it list by category, or just alphabetical.

**Comment by ehodul** [comment]
It seems to be useful to have it displayed by category as people who are searching do not need to know the exact program name.

**Comment by ucem** [comment]
How much time would it take to create the same module (displayed as it currently is) but with 2 or 3 columns.

**Comment by ehodul** [comment]
To add another block to the module to display data in 2 columns would take roughly 2 hours (or less) for development, styling and testing.

**Comment by ucem** [comment]
Ok, we'll hold off on it for now.  Thanks.

**Comment by ucem** [comment]
We'd like to move forward with this as soon as you can get it on your schedule.  Thanks!

**Comment by ehodul** [comment]
I will work on this next week.

**Comment by ehodul** [comment]
I created a new block:
"Programs Offered - categorized, displayed in 2 columns"
you can place it on school page (specify pages in 'Show block on specific pages' settings). Please let me know if this works as expected.

**Comment by ucem** [comment]
I placed it on the programs page and that's what I was looking for!  Can we force better spacing between the categories?  Its good between the Art and Design programs and Business, but is too close together between the end of the business programs and the next Category Titles.
![screen shot 2017-01-16 at 11 24 19 am](https://cloud.githubusercontent.com/assets/2644526/21996312/81fdc450-dbde-11e6-8552-17055e16a2f7.png)

**Comment by ehodul** [comment]
Updated. Please review.

**Comment by ucem** [comment]
Its great, thanks!!
