### ISSUE TITLE
Career Page - Dividing by Country

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#163]
On May 9, 2016 we discussed dividing the career page for Canada and the US and you added a country field to the career page.  Correct me if I'm wrong but I think that only serves as an internal way for us to know which country that taxonomy should be used for, is that correct?  

We also tried having two career taxonomy (Accounting - for Canada) and (Accounting in the US).  Unfortunately this really doesn't work.  While the page /careers page is only reachable by visits on this page /areas-of-study, or through the breadcrumbs,  it makes for a very long list.  

In Issue # 150, we discussed dividing the career page by province etc. but for now wondering if we could divide by Country only and perhaps having map icons at the top of the page and if the user wanted to see the schools in the us, they would click on the map and it would jump down to the US section, instead of having to scroll down.

Thoughts?

**Comment by ehodul** [comment]
The Country field in the taxonomy (Careers) might not be currently used. 
We can divide career page by country (Canada first, then US).

**Comment by ucem** [comment]
how much time would it take?

**Comment by ehodul** [comment]
It would take 2 hours to complete.

**Comment by ucem** [comment]
Thanks, need to think about this and decide after we complete the new client web form issue.
