### ISSUE TITLE
Webform - Download Issues and Alphabetical Listing

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#164]
The Webforms are no longer listed alphabetically and you had mentioned that it can be done here. /admin/content/webform but I couldn't figure out where to go from there.

Also, when downloading leads, if you select only the most recent in download range options, only the headers download, to get the content, I have to download all submissions.  Not a big deal, but a nuisance. 
![screen shot 2017-01-03 at 11 42 51 am](https://cloud.githubusercontent.com/assets/2644526/21620594/f793f00c-d1a9-11e6-97a0-fbbe55707190.png)

**Comment by ehodul** [comment]
I updated webforms module to add the sorting.
I was not able to find any information on the download range. Is this a new issue (latest webform module update), or was it like this before?

**Comment by ucem** [comment]
Sorting issue - thanks, where do I sort it if it happens again.  It seems to reoccur and I can never figure it out.
Download - yes its a new issue.  It started about a month ago.

**Comment by ehodul** [comment]
These two issues are related to webform module update that was done recently. 
Sorting issue: I added the sorting directly to the module as it was the fastest way, we can also add this in a custom module (that way we will keep the sorting regardless of webform module update).
Download: I will investigate some more, there will most probably be a fix issued for this issue in the next version of the webform module.

**Comment by ucem** [comment]
Thanks, not urgent though.
