### ISSUE TITLE
Careers Page

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#165]
I updated the content in node/266 and when I saved it, it goes to /careers-0 instead of /careers

When you go to /careers the view got really messed up.

**Comment by ehodul** [comment]
Path /careers is already taken by the Taxonomy vocabulary Careers. 
When automatic URL alias was generated for this page (titled 'Careers'), it added '-0' at the end of the path to 'careers-0'. Perhaps what is needed here is to disable automatic URL alias and add a new related available URL alias.
Where should be the content of node/266 displayed?

**Comment by ucem** [comment]
It should remain looking like this, except with the updated content in node/266.
/evolve/careers

**Comment by ehodul** [comment]
I see. This is fixed, please review '/careers' now.

**Comment by ucem** [comment]
Looks good.  What happened to cause it (i.e.. what did I do?) :-(

**Comment by ehodul** [comment]
You did nothing wrong. There was a collision between paths, as multiple entities claimed the '/careers' path. By editing the page (node/266) the system tried to correct this (by assigning careers-0 to current page). All is well now, the subsequent editing of the page should be OK.
