### ISSUE TITLE
Parse Codes 

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#166]
![screen shot 2017-01-24 at 12 31 33 pm](https://cloud.githubusercontent.com/assets/2644526/22265486/1f566cb8-e231-11e6-881c-da67c98c0a40.png)

I will send campuses and codes via email

**Comment by ucem** [comment]
I've submitted tests and all is ok except for the parsed codes, so its ready for you to do your magic in the back end!

**Comment by ehodul** [comment]
Done. Please review.

**Comment by ucem** [comment]
It appears to be working, thanks very much.

**Comment by ucem** [comment]
Question:  Codes have been changed from letters such as MAM to full text such as Associate of Applied Science in ..... will our parsing still work?
