### ISSUE TITLE
Sandbox - Image Library

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#167]
At your convenience can you please fix the issue so we can see the Image library like you did with the live site. No rush.  Thanks!

**Comment by ehodul** [comment]
Could you please remind me what was the issue or send me the live link? Thanks!

**Comment by ucem** [comment]
![screen shot 2017-01-31 at 3 22 43 pm](https://cloud.githubusercontent.com/assets/2644526/22488850/2ad9b53e-e7c9-11e6-8595-13b3dd6539b0.png)


![screen shot 2017-01-31 at 3 21 05 pm](https://cloud.githubusercontent.com/assets/2644526/22488809/f7a746fe-e7c8-11e6-96d4-9cffc8ba56a9.png)

**Comment by ehodul** [comment]
Done. Please review.

**Comment by ucem** [comment]
Works great, thank you.
