### ISSUE TITLE
Career Image

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#168]
I know we discussed image sizes during a call, but I can't seem to get it to work for Career Pages.  

Structure - Taxonomy - careers
Manage Display

Played with all variations, I'm still only getting an image on the left side of the page.  I know we did that on the old site, but I'm playing with images and wanted to see what it would look like to use original image like we do with content types.

**Comment by ehodul** [comment]
Career pages are special - they are generated in the search_by_career module. The image style and position is set in the module as well. I can change the module to use original image if needed. Alternatively, we can figure out how to read current field setting (for image style display) and modify the module to use this style.

**Comment by ucem** [comment]
Can we try your first option in the sandbox site so I can see how it looks.  Is it a lot of work?

**Comment by ehodul** [comment]
Yes, we can try in the sandbox, not a lot of work.

**Comment by ucem** [comment]
Sure, lets give it a try.

**Comment by ehodul** [comment]
Please review:
http://www.universities-colleges-schools.com/evolve/career/3d-modeling

**Comment by ucem** [comment]
Thanks, this looks good, go ahead and make this change to the live site.

At some later point in time, maybe we'll look into your second option if needed.
(Alternatively, we can figure out how to read current field setting (for image style display) and modify the module to use this style.)

**Comment by ehodul** [comment]
This is done. Please review.

**Comment by ucem** [comment]
Looks great, thank you!

**Comment by ucem** [comment]
I think I jumped the gun on this.  Looking at some of the images on the career pages, and they don't look good.  eg. career/dental-assistant , /career/massage-therapy (too pixelated) 

I looked at the custom module and there is no "configure" button, so I'm assuming that module is pure programming?  Is there somewhere where I could change the image size?  Or can you change it back to what it was and I'll make sure images are that size for now?
Thanks.

**Comment by ehodul** [comment]
I put it back to what it was before:
image style medium_blog (320x219) floating left.

**Comment by ucem** [comment]
Thanks for doing it so quickly.  Later on we'll maybe look at your earlier suggestion.

"Alternatively, we can figure out how to read current field setting (for image style display) and modify the module to use this style."
