### ISSUE TITLE
Space Needed on School & Program Pages

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#169]
Could you force an additional space each between the logo and header image, and between the header image and body on both school and program pages.  Regardless of whether we use a header image or not, the body nestles up too close.
![screen shot 2017-02-14 at 4 46 11 pm](https://cloud.githubusercontent.com/assets/2644526/22956157/2a148932-f2d5-11e6-8d7b-4dd213a3a858.png)

**Comment by ehodul** [comment]
Done.

**Comment by ucem** [comment]
Looks great, thanks!

**Comment by ucem** [comment]
It looks like the space you added has disappeared for some reason.  Is there someway I can do this myself if it occurs again?

**Comment by ucem** [comment]
It looks like the space you added has disappeared for some reason.  Is there someway I can do this myself if it occurs again?

**Comment by ucem** [comment]
It looks like the space you added has disappeared for some reason.  Is there someway I can do this myself if it occurs again?

**Comment by ucem** [comment]
It looks like the space you added has disappeared for some reason.  Is there someway I can do this myself if it occurs again?

**Comment by ehodul** [comment]
I added the space again - margin 10px top and bottom. PLease review.

**Comment by ucem** [comment]
Could you do it for the program pages as well?

**Comment by ehodul** [comment]
Could you please send me a link to program page that needs to be adjusted? I just can't find any program with header image. Thanks!

**Comment by ucem** [comment]
I think both are good now, thanks!
