### ISSUE TITLE
New Posting Instructions Webform Node 1289

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#170]
![screen shot 2017-02-27 at 11 53 01 am](https://cloud.githubusercontent.com/assets/2644526/23377064/55fb8ec0-fce3-11e6-8d07-b0cba1372133.png)

Instructions coming via email

**Comment by ucem** [comment]
Is there a phone validation module that we could use? Just wondering as often people don't read the instructions under the phone field to not use spaces or dashes and then leads are rejected if phone numbers are cut off.  Is that overkill?  Would prefer not to have to program in back end.

drupal.org/project/phone

**Comment by ehodul** [comment]
We can add a front end JavaScript validation for the phone if needed.

**Comment by ehodul** [comment]
We used to have the phone formatting for Trillium college on the old site, maybe we could just reuse it. Please have a look at the old site: 
/old/request-information/trillium-college-kingston

**Comment by ucem** [comment]
I looked at the source code, as I couldn't easily find their instructions, but I'm assuming the phone number had to be 10 digits.  If so, please go ahead and add to the forms I will specify in an email.
