### ISSUE TITLE
IsTest True/False vs Yes/No

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#175]
CurriculumID for client is 6 digits, however, only last 4 digits are transmitted. 

Will send you the query string and details in an email.

Thanks!

**Comment by ucem** [comment]
I might have found the error :-(.  Will let you know

**Comment by ucem** [comment]
Query string works now, changed title to IsTest and sent info via email.

**Comment by ehodul** [comment]
Done. Updated submitted value of 'IsTest'. Please review.

**Comment by ucem** [comment]
Test went in, looks good.  thanks!
