### ISSUE TITLE
PHP Notice - Undefined index: field...

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#176]
![screen shot 2017-05-07 at 12 35 40 pm](https://cloud.githubusercontent.com/assets/2644526/25784428/ba9b725e-3321-11e7-81b7-6f2d598e3450.png)

I've been seeing a lot of these, just wondering what it means and if there is anything to be concerned about.

**Comment by ehodul** [comment]
This should be fixed now. It was just a notice that the Quinstreet widget field is not available (on some pages).

**Comment by ucem** [comment]
Thanks!
