### ISSUE TITLE
Media Security Update

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#177]
Will leave this up to you to determine if we should update or not!

Media (Security update)	7.x-1.6	7.x-2.0 (Release notes)
This update is a major version update which means that it may not be backwards compatible with your currently running version. It is recommended that you read the release notes and proceed at your own risk.

**Comment by ehodul** [comment]
I saw it, but have not done the update, I am not sure if the new version works well with the Layer Slider and other theme elements that we currently use. I will do the update on the test site first to make sure it all works.

**Comment by ucem** [comment]
thanks, no rush.

**Comment by ehodul** [comment]
I updated the TEST (evolve) site and now there is an error when editing slides. I will have to figure out what can be done to fix (before updating the live site) it or revert to the old version.

**Comment by ucem** [comment]
easier to revert to old site on evolve?  Will they be issuing a better update?

**Comment by ehodul** [comment]
I will do some research, there must be a way to do this. If not, then I will revert test site and wait for a better update on live.
