### ISSUE TITLE
Leads not Emailed

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#178]
It looks like we have the issue of the system not sending out email notification with a lead is submitted again.  The last time the system was sending out emails was on July 19th.
Can you please have a look?
Thanks!

**Comment by ehodul** [comment]
Could you please give me more detail? Thanks!

**Comment by ucem** [comment]
When a lead is transmitted we have set it up so that we get notification via email as well, but they stopped getting sent automatically.  We had this issue when we first set the new site up, not sure what you did to fix it.  (I will forward you a copy of the email where we originally discussed this).

**Comment by ehodul** [comment]
I tested this on three different forms, including the Eastern College webform submission. All three sent emails to me (as I added my email to the webform email recipients for this test). It seems to be working as expected, other than the fact, that all these notification emails ended up in my Spam folder.

**Comment by ucem** [comment]
Interesting.  Checked my gmail spam folder and there they are.  They were not coming into my phone nor outlook. I had checked the regular gmail folders which is where they've always gone, but didn't check the Spam folder.  Weird that Gmail all of a sudden considered them spam. 👎 
Thanks!
