### ISSUE TITLE
Apostrophe Causing Leads to be rejected

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#179]
Issue is still with apostrophe mark. Use exactly as(Tried from formpost doc as well; same result): 'Bachelor's Degree'; Encoding to: Bachelor%27s%20Degree.
 
Yours in the lead is: Bachelor%E2%80%99s+Degree; so something wrong with the apostrophe mark. Some setting issue on your tool/Browser.

Will send you details in an email so that its not public.

**Comment by ehodul** [comment]
The problem was wrong apostrophe in the webform component EducationLevel.

Wrong value (encodes to %E2%80%99):
Master’s Degree|Master’s Degree

Good value (encodes to %27):
Master's Degree|Master's Degree
