### ISSUE TITLE
AdSense Reports

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#180]
Could you tell me how I can enable the AdSense reports so I can see which pages are getting clicks?

/admin/reports/adsense

thanks

**Comment by ehodul** [comment]
I believe AdSense click tracking is enabled (/admin/config/services/adsense/click) with your publisher ID and you can view results in Google AdSense reporting. It seems that the AdSense reporting in Drupal does not work (as the links in Google ads are generated by Google and Drupal module can not easily step in between and count clicks). 

This is what I found about the issue:
https://www.drupal.org/node/1174560
https://drupal.stackexchange.com/questions/74454/tracking-outbound-google-adsense-clicks
