### ISSUE TITLE
Lead Submission Return Message

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#181]
Can you please look at why we're getting this return message (don't want to list actual name since this is public!!)

We changed Posting URL on Sunday; test lead submitted that day returned message of "Return code 200 ok",  (1st image) today its returning a message with a different school name (second image).
![test lead 1](https://user-images.githubusercontent.com/2644526/30339087-bea8d4be-97a2-11e7-8f4a-204f1b12ba3a.png)

![test lead 2](https://user-images.githubusercontent.com/2644526/30339089-c1f1612c-97a2-11e7-9db2-e5c808ce18e0.png)

**Comment by ehodul** [comment]
The notice is misleading. It seems like Sprott Shaw changed their response message and now the return data appears to be the same as we expect for Trillium college. I fixed the notice wording in the code - we no longer associate this response with Trillium.

**Comment by ucem** [comment]
Great, thanks!
