### ISSUE TITLE
Custom Breadcrumb Issue

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#182]
Noticed when adding a school, custom breadcrumb doubles the URL www.univer..... so when you click on the breadcrumb it takes you to a 404 page. 
In the past I created redirections but hoped you could have a look at it. 

![screen shot 2017-09-14 at 1 32 54 pm](https://user-images.githubusercontent.com/2644526/30454454-3d9a8baa-9951-11e7-8858-69ee24faa653.png)

![screen shot 2017-09-14 at 1 34 17 pm](https://user-images.githubusercontent.com/2644526/30454510-6f34f196-9951-11e7-9aac-3f88e477107d.png)

**Comment by ehodul** [comment]
I believe I fixed the URL - I modified the Program pages breadcrumb settings. Please review.

**Comment by ucem** [comment]
Works now, thanks!
