### ISSUE TITLE
Teaser Break

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#189]
Could you please activate Teaser Break in ALL content types (including "programs by geography"), like you did in the career taxonomy pages?
Thanks  
![screen shot 2018-01-17 at 2 25 47 pm](https://user-images.githubusercontent.com/2644526/35070551-7f85dab2-fb92-11e7-9c9f-7c79391efd6f.png)

**Comment by ehodul** [comment]
Please let me know what do you mean by 'activate Teaser Break'. Teaser Break is available by default in all fields type "Long text" and "Long text and summary" and Teaser is used as display format in views or in Teaser display.

Is there any particular situation when we need to apply teaser break and it is not working as expected?

**Comment by ucem** [comment]
When a teaser break is inserted, it doesn't actually put a break in like it does in the career taxonomy. I recall on the old site you did something to activate it. If you check the programs by geography page( hvac) I tried it and it didn't work .

**Comment by ucem** [comment]
Hi, just wondering if you will be able to look at this in the next few days?
