### ISSUE TITLE
Google Webmaster Tools Access

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#79]
You may have seen an email come through with access to Webmaster Tools.  I looked at our site speed using Page Speed Insights (under other resources) and we didn't get a very good ranking. 70/100 on desktop and 52/100 on Mobile.

Please have a look at their suggestions at your convenience and let me know what this entails, time required etc. Thank you!

**Comment by ucem** [comment]
When you have a chance can you log in and review some of the compression suggestions?  We have very poor Page Timings, even worse than our old non-responsive site.

**Comment by ehodul** [comment]
Hi Verna,
could you please send me the link to the page timings statistics?

**Comment by ehodul** [comment]
I added basic caching and aggregation of JavaScript and CSS files:
https://www.dropbox.com/s/axeqp22tsfy79o6/Screenshot%202017-06-14%2013.56.58.png?dl=0
