### ISSUE TITLE
Career Page Modification

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#94]
We've discussed various scenarios for landing pages on a sub-domain (#82) but were wondering how difficult it would be to modify the career page as follows:

Remove the Blocks from the right side of the page and replace with a dynamic lead form as per the .pdf document i will send via email.

A drop down menu would appear at the top with the schools offering the programs on the career page. For. eg. Administrative Assistant.  We would have them select a school from a drop down menu (CDI, Vancouver Career College, Reeves, MTI etc.).  Once they select the school, (eg. CDI) the lead form from CDI would be generated, or if they chose MTI, MTI's lead form would be generated.  The Program options could only have  the programs the school offers in that career (Business Administrative Professional, Computer Business Applications Specialist etc.) or it could contain all the program offerings.  Don't know if this is doable, and if so what it would entail.

**Comment by ehodul** [comment]
Please review the changes here and let me know if this works as requested:
http://dropideas.com/ucs/career/Accounting/248

**Comment by ucem** [comment]
1. Can you remove the locations and
2. Is it possible to only offer the programs from the drop down menu that are associated with this career?

**Comment by ehodul** [comment]
1. Do you mean to remove locations from the webform? 
2. I can try to modify the webform and only show programs associated with this career.

**Comment by ucem** [comment]
Not from the web form but those below the school name.  
![screen shot 2015-01-06 at 10 14 53 am](https://cloud.githubusercontent.com/assets/2644526/5633496/f5ec637a-958c-11e4-8b10-07750c5fb4d5.png)

As for the web form, if you modify to show only programs with the career, will it impact the original web form that shows in the school and program pages?

**Comment by ehodul** [comment]
1. Sure, I will remove these locations below the school name.
2. This might not be easily done and needs to be tested properly.

**Comment by ucem** [comment]
Thanks, let me know how it goes

**Comment by ehodul** [comment]
Done. Please review and let me know when to move to live site.

**Comment by ucem** [comment]
Looks great!  Please go ahead and move to live site.

**Comment by ehodul** [comment]
Done.

**Comment by ucem** [comment]
I think we have an error, when I select a school and program it takes me to the test site.
http://dropideas.com/ucs/career/Accounting/280

**Comment by ehodul** [comment]
Thanks! Fixed. Sorry for that.

**Comment by ucem** [comment]
Great!  One more quick thing.  Can you change the school default to say - Select- instead of it defaulting to the first on the list?

**Comment by ehodul** [comment]
I can do that, but does it mean that no webform should be shown (no school selected) at the beginning? That would be lots of empty space.

**Comment by ucem** [comment]
Oh....let's leave it as is then.  thank you!

**Comment by ucem** [comment]
Looks like one more issue.  The image size dimension limitations will have to be changed.

http://www.universities-colleges-schools.com/career/Actor

**Comment by ehodul** [comment]
Fixed. Good catch! Thanks!

**Comment by ucem** [comment]
Modifications
1. I couldn't figure out where to change the title on this block "Request information from schools offering this career" to "Request information from any of the schools who offer programs & courses for this career"  

2. Above the school could you add a header, saying “Select a Preferred College*".  Users might not notice the fact that its a drop down menu and think they can only request info from the school that shows in the menu.

Question
Is there a quick way to force selected schools or rank them so they show first on the page?  Currently there are two schools that usually show first (I won't name them in case a google alert goes out!!), but you can see who I mean by the attached image.  They are not playing nice (not paying their bills) and I don't want them to be first on the list.
![screen shot 2015-02-16 at 12 54 19 pm](https://cloud.githubusercontent.com/assets/2644526/6219180/11275848-b5db-11e4-8c98-dd790c04472b.png)

**Comment by ehodul** [comment]
I changed the title and added label for school select.
There is no quick way for ranking schools. I can sort them somehow, perhaps alphabetically.

**Comment by ucem** [comment]
How is it determined now?

**Comment by ehodul** [comment]
Right now it is not sorted in any way. Whatever the query returns, is displayed. First all the referencing programs are returned based on career term, then all schools are found for each program.

**Comment by ucem** [comment]
Looking at the various career pages, it "appears" that they are returned in the order the nodes were added.  I can't be sure unless I go through each one but that's how it looks.

Can you put some thought into what we could do to add a ranking system perhaps at the school level which would then determine how they are returned in the results?  Maybe a ranking scale of tiers 1-5.  We often add schools that are not yet clients in the hopes that if we demonstrate an ability to produce leads, they will sign up.  Non-paying schools would be ranked tier 5, with the schools we really want to promote, being a tier 1.  A school ranked 4, would be a school like the two I showed above, a signed client, but one that we really don't want to push too much.

**Comment by ehodul** [comment]
Sure, we can add a ranking scale for each school as you suggest. I can add a new field to school content type and modify 'search by career' result order (sort by school rank).

**Comment by ucem** [comment]
Could you tell me how many hours that would take?

**Comment by ehodul** [comment]
2 hours max., if we only add it to 'search by career' result page (not the whole site).

**Comment by ucem** [comment]
Oh that's good, let's do it.  Talking to one of the guys here, he wants us to go 1 - 10 instead of 1-5. 

Let me know when you can do it!

**Comment by ucem** [comment]
How will it display 2 schools if both are ranked a 1, will be it alphabetically?

**Comment by ehodul** [comment]
We can add that (alphabetical order), or leave current 'sorting' if all ranked the same.

**Comment by ucem** [comment]
For now, if all ranked the same, let's leave current sorting as is, and we can always add alphabetical if needed later on.  Thanks.

**Comment by ehodul** [comment]
Sort order added based on ranking. Please review career pages.

**Comment by ucem** [comment]
Noticed that on lead form on the right, the original listed school is shown first on the list.  Can you make it so that the Preferred School drop down shows in that same order?

**Comment by ehodul** [comment]
Done. Sorted the school dropdown in the block that is in the right sidebar.

**Comment by ucem** [comment]
Looks great, thank you!
